GET https://obscure-eyrie-42477.herokuapp.com/api/v1/flower

###
POST https://obscure-eyrie-42477.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "sepalLength": 21,
  "color": "blue",
  "price": 213
}